import type { LangCode } from "@/config/languages";

type KaigoServiceCopy = {
  title: string; description: string; heroAlt: string; lead: string;
  servicesTitle: string; services: readonly string[]; specialistScope: string;
  employmentTitle: string; employmentIntro: string; employmentChecks: readonly string[]; staffingLink: string;
  nightTitle: string; nightIntro: string; nightItems: readonly string[]; nightNote: string;
  openingTitle: string; openingHeadings: readonly string[]; openingRows: readonly (readonly string[])[]; deadlineNote: string;
  beforeOpeningTitle: string; beforeOpening: string;
};

/** Existing staffing/night-duty/opening information retained in all four locales. */
export const KAIGO_SERVICE_COPY: Record<LangCode, KaigoServiceCopy> = {
  ja: {
    title: "介護・障害福祉・グループホームの人事労務",
    description: "介護・障害福祉・グループホームの開設後の給与計算・社会保険・採用条件の相談を、人事部丸投げプランで支援。人員配置、就業規則、シフト、処遇改善の賃金設計もご相談いただけます。開設・指定申請は行政書士業務として別契約です。",
    heroAlt: "介護・障害福祉の労務管理のイメージ（事業所のシフト表）",
    lead: "介護・障害福祉事業所では、人員体制と指定基準・加算要件との整合が重要です。四葉社会保険労務士事務所は、開設後の給与計算・通常手続・労務相談に加え、人員配置を踏まえた就業規則やシフトの設計をご相談いただけます。",
    servicesTitle: "どんなことを頼めますか？",
    services: ["毎月の給与計算、通常の社会保険・雇用保険手続、日常的な労務相談", "採用条件・求人票の相談、雇用契約・労働条件通知書のレビュー", "就業規則・賃金規程の作成・見直し（夜勤・宿直・変形労働時間制への対応を含む）", "人員配置基準を踏まえたシフト・勤怠の運用設計", "処遇改善加算の賃金要件に沿った規程の整備・賃金改善額の算定支援", "労災など、通常手続以外の個別手続の相談"],
    specialistScope: "上記のうち就業規則・賃金規程の作成や見直し、処遇改善の賃金設計・算定支援等は、月額に一律に含まれるものではありません。既存規程や事業所の状況を確認し、作業範囲と費用を着手前にご案内します。シフト・勤怠の運用設計は、毎月の勤怠集計や打刻修正の代行とは別です。",
    employmentTitle: "世話人は常勤と非常勤、どちらで雇うべきですか？",
    employmentIntro: "どちらが良いと一律には決まりません。判断の材料になるのは次の4点です。",
    employmentChecks: ["指定基準上、そのサービス種別で常勤の配置が求められている職種かどうか", "常勤換算の分母となる所定労働時間を、就業規則でいくらに定めているか", "社会保険の被保険者となる勤務時間・日数の条件を満たすかどうか", "夜間の支援体制を組む場合、交替制にするか宿直で対応するか"],
    staffingLink: "人員基準と労務：常勤換算と就業規則の関係",
    nightTitle: "夜間支援は、労働時間としてどう扱われますか？",
    nightIntro: "夜間の勤務は、実際の働き方によって扱いが変わります。一般的には次のように整理されます。",
    nightItems: ["夜勤：通常の業務を行う時間帯。全体が労働時間となり、深夜（原則22時から翌5時）の割増賃金の対象になります（労働基準法第37条第4項）。", "宿直：常態としてほとんど労働する必要のない勤務。所轄労働基準監督署長の許可を受けた場合に、労働時間や休憩の規定の適用が除外されるとされています（労働基準法第41条第3号）。", "仮眠・待機：呼び出しに備えて待機している時間が労働時間にあたるかどうかは、拘束の程度によって判断されます。"],
    nightNote: "宿直の許可を受けずに宿直として扱うと、後から未払賃金の問題になる場合があります。許可の要否と申請は、面談のうえご案内します。",
    openingTitle: "開設するとき、就業規則と社会保険はいつまでに整えますか？",
    openingHeadings: ["やること", "時期の目安", "根拠・備考"],
    openingRows: [["労働条件の明示", "雇用契約を結ぶとき", "労働基準法第15条第1項"], ["就業規則の作成・届出", "常時10人以上の労働者を使用するに至ったとき", "労働基準法第89条。10人未満でも指定基準や加算の要件で必要になる場合があります"], ["社会保険の新規適用", "適用事業所に該当したとき", "健康保険法・厚生年金保険法。届出の期限は事実の発生から定められています"], ["労働保険の成立", "労働者を雇い入れたとき", "労働保険徴収法・雇用保険法"]],
    deadlineNote: "届出の具体的な期限は、面談のうえご案内します。新規適用・保険成立などの開設時手続は月額と別料金です。",
    beforeOpeningTitle: "これから開設する事業者も相談できますか？",
    beforeOpening: "できます。開設の準備では、物件・指定申請・労務体制の3つを整理します。物件は四葉不動産株式会社、指定申請の書類作成は四葉行政書士事務所、労務体制は当事務所がそれぞれ別契約で受任します。3事務所は同じ所在地にありますが独立した事業体で、料金・請求も分かれます。必要な部分だけをご依頼いただけます。",
  },
  en: {
    title: "HR for care, disability-welfare providers and group homes",
    description: "Payroll, routine insurance procedures and hiring-terms advice after opening, through our Outsourced HR Department Service. Consult us on staffing, work rules, shifts and treatment-improvement wage design. Opening and designation applications are separate administrative scrivener engagements.",
    heroAlt: "A workplace shift roster representing labor management for care and disability-welfare providers",
    lead: "Care and disability-welfare providers need staffing arrangements consistent with designation and add-on requirements. 四葉社会保険労務士事務所 supports payroll, routine procedures and labor consultations after opening, and advises on work rules and shift design in light of staffing needs.",
    servicesTitle: "What can you ask us to handle?",
    services: ["Monthly payroll, routine social and employment insurance procedures, and day-to-day labor advice", "Advice on hiring terms and job postings, and review of contracts and notices of working conditions", "Preparing and revising work and wage rules, including night work, overnight duty and variable working hours", "Designing shift and attendance workflows with staffing standards in view", "Preparing wage rules and supporting wage-improvement calculations for treatment-improvement add-ons", "Consultations on individual procedures outside routine coverage, including workers’ compensation"],
    specialistScope: "Work-rule and wage-rule drafting or revision, treatment-improvement wage design and calculation support are not automatically included in the monthly fee. We check existing rules and your circumstances and explain the scope and fees before work begins. Designing attendance workflows is separate from monthly attendance aggregation or clock-in corrections.",
    employmentTitle: "Should group-home support staff be full-time or part-time?",
    employmentIntro: "There is no single answer for every provider. Four useful considerations are:",
    employmentChecks: ["Whether the designation standards for your service require a full-time appointment for the role", "The prescribed working hours in the work rules used as the denominator for full-time-equivalent staffing", "Whether the employee’s working hours and days meet social insurance eligibility conditions", "Whether night support uses shifts or overnight duty"],
    staffingLink: "Staffing standards and labor: full-time equivalents and work rules",
    nightTitle: "How is night support treated as working time?",
    nightIntro: "Treatment depends on the work actually performed. The general distinctions are:",
    nightItems: ["Night shifts: time spent performing ordinary duties counts as working time. Work during statutory late-night hours, generally 22:00–05:00, attracts a premium (Labor Standards Act, Article 37(4)).", "Overnight duty: work requiring almost no activity under ordinary circumstances. With permission from the competent Labor Standards Inspection Office, working-time and rest-break provisions may be disapplied (Labor Standards Act, Article 41(3)).", "Naps and standby: whether time spent waiting to respond to calls counts as working time depends on the degree of restriction."],
    nightNote: "Treating work as exempt overnight duty without permission can lead to unpaid-wage issues. We discuss whether permission and an application are needed during consultation.",
    openingTitle: "When should work rules and insurance be arranged for opening?",
    openingHeadings: ["Task", "Timing guide", "Basis and notes"],
    openingRows: [["Notice of working conditions", "When concluding the employment contract", "Labor Standards Act, Article 15(1)"], ["Preparing and filing work rules", "When regularly employing 10 or more workers", "Labor Standards Act, Article 89. Designation or add-on requirements may also matter below 10 workers"], ["Initial social insurance registration", "When the workplace becomes subject to coverage", "Health Insurance Act and Employees’ Pension Insurance Act; filing periods run from the relevant event"], ["Establishing labor insurance", "When workers are hired", "Labor Insurance Premiums Collection Act and Employment Insurance Act"]],
    deadlineNote: "Specific filing deadlines are explained during consultation. Opening procedures such as initial registration and establishing coverage carry separate fees.",
    beforeOpeningTitle: "Can a provider that has not opened yet consult you?",
    beforeOpening: "Yes. We help organize property, designation applications and labor arrangements. 四葉不動産株式会社 handles property, 四葉行政書士事務所 prepares designation application documents, and our office handles labor matters under separate contracts. The three offices share an address but are independent businesses with separate fees and invoices. You can engage only the services you need.",
  },
  "zh-tw": {
    title: "照護・障礙福祉・團體家屋的人事勞務",
    description: "透過人事部全包方案支援開設後的薪資計算、一般社會保險手續與招聘條件諮詢。亦可諮詢人員配置、就業規則、排班及處遇改善的薪資設計。開設與指定申請以行政書士業務另行簽約。",
    heroAlt: "照護・障礙福祉勞務管理示意圖（事業所排班表）",
    lead: "照護與障礙福祉事業所，須重視人員體制與指定基準、加算要件之間的整合。四葉社会保険労務士事務所除開設後的薪資計算、一般手續與勞務諮詢外，也接受兼顧人員配置的就業規則與排班設計諮詢。",
    servicesTitle: "可以委託哪些工作？",
    services: ["每月薪資計算、一般社會保險與雇用保險手續、日常勞務諮詢", "招聘條件與職缺諮詢、雇用契約及勞動條件通知書的審閱", "就業規則與薪資規程的製作、修訂（含夜班、宿直與變形工時制）", "兼顧人員配置基準的排班與出勤作業流程設計", "依處遇改善加算的薪資要件整備規程，支援薪資改善額計算", "職災等一般手續範圍外的個別手續諮詢"],
    specialistScope: "就業規則、薪資規程的製作或修訂，及處遇改善的薪資設計與計算支援等，並非一律包含於月費。確認現有規程及事業所情況後，會在著手前說明工作範圍與費用。排班與出勤流程設計，與每月出勤彙整、打卡修正代辦是不同工作。",
    employmentTitle: "團體家屋的世話人應採常勤還是非常勤？",
    employmentIntro: "無法一概而論。可從以下4點整理判斷材料。",
    employmentChecks: ["該服務類別的指定基準，是否要求此職種配置常勤人員", "就業規則所定的工時為何，亦即常勤換算的分母", "工作時數與天數是否符合社會保險被保險人的條件", "夜間支援採輪班還是宿直方式"],
    staffingLink: "人員基準與勞務：常勤換算及就業規則的關係",
    nightTitle: "夜間支援如何計入工作時間？",
    nightIntro: "處理方式依實際工作狀況而異。一般可作以下區分。",
    nightItems: ["夜班：執行一般業務的時段，整體屬工作時間；深夜原則為22時至翌日5時，涉及深夜加成工資（勞動基準法第37條第4項）。", "宿直：平時幾乎無需工作的勤務。經主管勞動基準監督署長許可後，可排除工時與休息規定的適用（勞動基準法第41條第3項）。", "小睡・待命：為應對呼叫而等待的時間是否屬工作時間，依受拘束的程度判斷。"],
    nightNote: "未取得宿直許可卻按宿直處理，日後可能產生未付工資問題。是否需要許可及申請方式，將於面談時說明。",
    openingTitle: "開設時，就業規則與社會保險應何時備妥？",
    openingHeadings: ["工作", "時機參考", "依據・備註"],
    openingRows: [["明示勞動條件", "締結雇用契約時", "勞動基準法第15條第1項"], ["製作及申報就業規則", "經常雇用10人以上時", "勞動基準法第89條。未滿10人，也可能因指定基準或加算要件而需要"], ["社會保險新規適用", "符合適用事業所條件時", "健康保險法・厚生年金保險法；申報期限由相關事實發生起算"], ["勞動保險成立", "雇用勞工時", "勞動保險徵收法・雇用保險法"]],
    deadlineNote: "各申報的具體期限，將於面談時說明。新規適用、保險成立等開設手續在月費之外另行收費。",
    beforeOpeningTitle: "尚未開設的事業者也能諮詢嗎？",
    beforeOpening: "可以。開設前需整理物件、指定申請與勞務體制。物件由四葉不動産株式会社、指定申請文件由四葉行政書士事務所、勞務體制由本事務所各自另行簽約承辦。3家事務所同址，但為獨立事業體，費用及請款亦分開。可僅委託所需部分。",
  },
  zh: {
    title: "护理・残障福祉・团体家屋的人事劳务",
    description: "通过人事部全包方案支持开设后的工资计算、一般社会保险手续与招聘条件咨询。亦可咨询人员配置、就业规则、排班及处遇改善的工资设计。开设与指定申请以行政书士业务另行签约。",
    heroAlt: "护理・残障福祉劳务管理示意图（事业所排班表）",
    lead: "护理与残障福祉事业所，须重视人员体制与指定基准、加算要件之间的一致性。四葉社会保険労務士事務所除开设后的工资计算、一般手续与劳务咨询外，也接受兼顾人员配置的就业规则与排班设计咨询。",
    servicesTitle: "可以委托哪些工作？",
    services: ["每月工资计算、一般社会保险与雇用保险手续、日常劳务咨询", "招聘条件与职位咨询、雇用合同及劳动条件通知书的审阅", "就业规则与工资规程的制作、修订（含夜班、宿直与变形工时制）", "兼顾人员配置基准的排班与出勤工作流程设计", "按处遇改善加算的工资要件完善规程，支持工资改善额计算", "工伤等一般手续范围外的个别手续咨询"],
    specialistScope: "就业规则、工资规程的制作或修订，及处遇改善的工资设计与计算支持等，并非一律包含于月费。确认现有规程及事业所情况后，会在着手前说明工作范围与费用。排班与出勤流程设计，与每月出勤汇总、打卡修正代办是不同工作。",
    employmentTitle: "团体家屋的世话人应采用全职还是非全职？",
    employmentIntro: "无法一概而论。可从以下4点整理判断材料。",
    employmentChecks: ["该服务类别的指定基准，是否要求此职种配置全职人员", "就业规则所定的工时为何，即常勤换算的分母", "工作时数与天数是否符合社会保险被保险人的条件", "夜间支持采用轮班还是宿直方式"],
    staffingLink: "人员基准与劳务：常勤换算及就业规则的关系",
    nightTitle: "夜间支持如何计入工作时间？",
    nightIntro: "处理方式依实际工作状况而异。一般可作以下区分。",
    nightItems: ["夜班：执行一般业务的时段，整体属工作时间；深夜原则为22时至次日5时，涉及深夜加成工资（劳动基准法第37条第4项）。", "宿直：平时几乎无需工作的值勤。经主管劳动基准监督署长许可后，可排除工时与休息规定的适用（劳动基准法第41条第3项）。", "小睡・待命：为应对呼叫而等待的时间是否属工作时间，按受约束的程度判断。"],
    nightNote: "未取得宿直许可却按宿直处理，日后可能产生未付工资问题。是否需要许可及申请方式，将于面谈时说明。",
    openingTitle: "开设时，就业规则与社会保险应何时备妥？",
    openingHeadings: ["工作", "时机参考", "依据・备注"],
    openingRows: [["明示劳动条件", "签订雇用合同时", "劳动基准法第15条第1项"], ["制作及申报就业规则", "经常雇用10人以上时", "劳动基准法第89条。未满10人，也可能因指定基准或加算要件而需要"], ["社会保险新规适用", "符合适用事业所条件时", "健康保险法・厚生年金保险法；申报期限由相关事实发生起算"], ["劳动保险成立", "雇用劳动者时", "劳动保险征收法・雇用保险法"]],
    deadlineNote: "各申报的具体期限，将于面谈时说明。新规适用、保险成立等开设手续在月费之外另行收费。",
    beforeOpeningTitle: "尚未开设的事业者也能咨询吗？",
    beforeOpening: "可以。开设前需整理物件、指定申请与劳务体制。物件由四葉不動産株式会社、指定申请文件由四葉行政書士事務所、劳务体制由本事务所各自另行签约承办。3家事务所同址，但为独立事业体，费用及收款亦分开。可仅委托所需部分。",
  },
};
