/** Emit only the article approved for publication; bank-service drafts stay server-only. */
import { writeFileSync } from "node:fs";
import { NONRESIDENT_COPY, NONRESIDENT_SOURCES } from "../src/lib/legal/nonresident-review-copy";
import { addLocalePrefix } from "../src/lib/locale";
import type { LangCode } from "../src/config/languages";
import type { ColumnInput, ColumnTranslation } from "../src/lib/column-shared";

const slug = "hikyojusha-kabushiki-setsuritsu-shihonkin-kouza";
const categories: Record<LangCode, string> = { ja: "会社設立", en: "Company incorporation", "zh-tw": "公司設立", zh: "公司设立" };
function article(locale: LangCode): ColumnTranslation {
  const c = NONRESIDENT_COPY[locale];
  return {
    title: c.articleTitle, excerpt: c.excerpt, category: categories[locale],
    content: [c.excerpt,
      ...c.articleSections.map(s => `## ${s.heading}\n\n${s.paragraphs.join("\n\n")}`),
      `## ${c.preparationTitle}\n\n| ${c.preparationColumns.join(" | ")} |\n|---|---|\n${c.preparation.map(row => `| ${row.join(" | ")} |`).join("\n")}`,
      `## ${c.faqTitle}\n\n${c.faqs.map(f => `**${f.question}**\n\n${f.answer}`).join("\n\n")}`,
      `## ${c.sourcesTitle}\n\n${NONRESIDENT_SOURCES.map((href, i) => `- [${c.sourceLabels[i]}](${href}) — ${c.sourceNotes[i]}`).join("\n")}`,
      c.independence, c.disclaimer,
      `[${c.serviceLink}](${addLocalePrefix("/legal/services/company", locale)}) · [${c.feeLink}](${addLocalePrefix("/legal/ryokin", locale)})`,
      `${c.author}\n\n[${c.authorLink}](${addLocalePrefix("/legal/about", locale)})`,
    ].join("\n\n"),
    author: { name: "浦松丈二", title: c.author.split(/[｜|]/)[1].trim() },
    tags: [categories[locale]], keywords: [c.articleTitle], faq: c.faqs,
  };
}
const ja = article("ja");
const columns: ColumnInput[] = [{
  ...ja, category: categories.ja, business: "legal", slug,
  date: "2026-10-06", modifiedDate: "2026-10-06", status: "published",
  ogImage: "/hero/legal-company-16x9.webp", locales: ["ja", "en", "zh-tw", "zh"],
  translations: { en: article("en"), "zh-tw": article("zh-tw"), zh: article("zh") },
}];
writeFileSync("src/lib/data/nonresident-company-column-seed.ts",
  '// Generated by scripts/seed-nonresident-company-column.ts. Public article only.\nimport type { ColumnInput } from "@/lib/column-shared";\n\nexport const NONRESIDENT_COMPANY_COLUMN_SEED: ColumnInput[] = ' + JSON.stringify(columns, null, 2) + ';\n');
console.log("Emitted one article in four locales; no database mutation.");
